
import React from 'react';
import { Scenario, ScenarioConfig, Document } from './types';
import { ChatIcon, CodeIcon, DocumentSearchIcon, WebSearchIcon } from './components/icons';

export const SCENARIO_CONFIGS: Record<Scenario, ScenarioConfig & { icon: React.FC<{className: string}> }> = {
  [Scenario.NORMAL]: {
    id: Scenario.NORMAL,
    title: 'Normal Chat',
    description: 'A standard conversation with an AI.',
    longDescription: 'Engage in a standard, free-flowing conversation. Explore how conversation history (the previous turns) becomes the context for each new response.',
    systemPrompt: 'You are a helpful and friendly conversational AI. Keep your responses concise and engaging. Crucially, you must always end your response with a question or a statement that invites the user to continue the conversation.',
    icon: ChatIcon,
    suggestions: [
        "Let's chat about my upcoming trip.",
        "I need help brainstorming ideas for a creative project.",
        "I'm facing a challenge at work, can we talk through it?",
        "I want to learn a new skill but don't know where to start.",
    ],
    suggestionDescription: "Try one of these prompts to start a conversation:",
  },
  [Scenario.DATA]: {
    id: Scenario.DATA,
    title: 'Data Analysis Chat',
    description: 'Ask questions that require calculations.',
    longDescription: 'Ask a question that requires a simple calculation (e.g., "What is 25% of 120?"). See how the model uses a "tool" (a code interpreter) to find the answer.',
    systemPrompt: 'You are a data analysis assistant. When the user asks a question that requires calculation, you must use the provided tool to get the answer.',
    icon: CodeIcon,
    suggestions: [
        "What is 15 * 24?",
        "Calculate the area of a circle with a radius of 5.",
        "What is 35% of 580?",
        "If a car travels 150 miles in 3 hours, what is its average speed?",
    ],
    suggestionDescription: "Try one of these questions to see the code interpreter work:",
  },
  [Scenario.SEARCH]: {
    id: Scenario.SEARCH,
    title: 'Search Chat',
    description: 'Ask about recent events or facts.',
    longDescription: 'Ask a question about a recent event or a topic that requires up-to-date information. The model will use Google Search to ground its response.',
    systemPrompt: 'You are an AI assistant that can browse the web. Answer the user\'s question using the provided search tool.',
    icon: WebSearchIcon,
    suggestions: [
        "Who won the latest Super Bowl?",
        "What are the top trending movies right now?",
        "What's the weather like in Tokyo?",
        "Summarize the latest news about space exploration.",
    ],
    suggestionDescription: "Try one of these questions to see Google Search in action:",
  },
  [Scenario.DOCUMENT]: {
    id: Scenario.DOCUMENT,
    title: 'Document Library Chat',
    description: 'Ask questions about a local set of documents.',
    longDescription: 'Ask questions based on a small, provided set of documents. This demonstrates Retrieval-Augmented Generation (RAG), where the AI\'s context is "augmented" with relevant information.',
    systemPrompt: 'You are an expert Q&A assistant. Answer the user\'s question based *only* on the provided document excerpts. If the answer is not in the documents, state that clearly. Do not use any prior knowledge.',
    icon: DocumentSearchIcon,
    suggestions: [
      "What is Project Titan and what is its budget?",
      "Who is the lead engineer for Project Titan?",
      "Tell me about the 'Nova' product launch.",
      "When and where is the annual company offsite?",
      "What was the revenue growth in Q2 2024?",
    ],
    suggestionDescription: "Try one of these questions about our mock document library:",
  },
};

export const MOCK_DOCUMENTS: Document[] = [
  {
    title: "Project Titan: A Strategic Infrastructure Overhaul",
    content: "Project Titan represents a monumental leap forward for our company's technological foundation. Launched in 2022, this multi-year initiative is designed to completely modernize our data infrastructure, ensuring we remain competitive and agile in an increasingly data-driven world. The project is not merely an update but a fundamental reimagining of how we store, process, and leverage data across all business units. The commitment to this vision is underscored by a significant initial investment, with a budget of $5 million allocated for the successful completion of Phase 1.\n\nThe core objective of Project Titan is to enhance scalability, improve security, and increase operational efficiency. By transitioning away from outdated, on-premise systems, we are positioning ourselves to handle exponential data growth and unlock new capabilities in analytics and machine learning. This strategic shift will empower our teams to develop more innovative products and deliver superior customer experiences. The long-term vision extends beyond simple migration, aiming to create a unified, intelligent data ecosystem that serves as a strategic asset for the entire organization.\n\nLeading this ambitious undertaking are Dr. Evelyn Reed, the lead engineer, and David Chen, the dedicated project manager. Their combined expertise in cutting-edge data architecture and large-scale project execution provides the strong leadership necessary to navigate the complexities of this initiative. They are responsible for steering the project toward its goals, managing resources effectively, and ensuring all technical and logistical milestones are met. Their leadership is crucial for maintaining momentum and alignment throughout the project's lifecycle.\n\nTo ensure complete transparency and keep all stakeholders informed, Dr. Reed and Mr. Chen deliver comprehensive weekly updates. These Friday briefings serve as a vital communication channel, offering insights into progress, highlighting recent achievements, and addressing any emerging challenges. This regular cadence of reporting fosters a collaborative environment, allowing for timely feedback and ensuring the project remains aligned with broader company objectives. It is a testament to the project's organized and accountable management structure.\n\nThe successful execution of Project Titan will have a transformative impact on our business. It will not only modernize our technological backbone but also cultivate a culture of innovation and data-centric decision-making. The capabilities unlocked by this new infrastructure will enable us to respond more quickly to market changes, anticipate customer needs, and ultimately, drive sustainable growth for years to come. This is more than an IT project; it is a foundational investment in our future success."
  },
  {
    title: "The 'Starlight' Campaign: Launching the 'Nova' Smart Hub",
    content: "The upcoming launch of our 'Nova' smart home hub will be supported by a dynamic and targeted marketing campaign, codenamed 'Starlight'. Scheduled to commence on August 15th, this campaign is meticulously designed to create significant market buzz and drive early adoption. With a dedicated budget of $2.5 million, 'Starlight' will employ a multi-channel strategy to ensure maximum reach and impact. The campaign's primary goal is to firmly establish 'Nova' as the leading next-generation smart home solution in the minds of consumers.\n\nOur target audience for the 'Nova' launch is the tech-savvy young adult demographic, specifically individuals aged 18-25. This group is known for being early adopters of new technology and highly influential within their social networks. By focusing our efforts on this segment, we aim to build a strong foundational user base that will generate organic growth through word-of-mouth and social media engagement. All marketing collateral, messaging, and channel selections have been tailored to resonate with the values and media consumption habits of this specific audience.\n\nThe core messaging of the 'Starlight' campaign will revolve around the 'Nova' hub's key differentiators: seamless voice control, extensive device compatibility, and its revolutionary adaptive learning module. We will highlight how these features create a truly intuitive and personalized smart home experience that anticipates user needs. The campaign will showcase real-world scenarios where 'Nova' simplifies daily routines, enhances home security, and provides unparalleled convenience, making advanced technology feel accessible and effortless.\n\nTo reach our target demographic effectively, the campaign will leverage a mix of digital-first channels. This includes major investments in social media advertising on platforms like Instagram and TikTok, collaborations with prominent tech influencers, and targeted content marketing through popular blogs and video platforms. We will also implement a robust public relations strategy to secure positive reviews and features in key technology publications, further building credibility and excitement ahead of the official product release.\n\nThe success of the 'Starlight' campaign will be measured through a variety of key performance indicators, including brand awareness metrics, lead generation, pre-order numbers, and initial sales data. We are confident that this well-funded, strategically targeted campaign will not only meet but exceed its objectives, ensuring the 'Nova' smart home hub has a spectacular market debut and secures a strong position against competitors."
  },
  {
    title: "'Nova' Smart Home Hub: Redefining Intelligent Living",
    content: "The 'Nova' smart home hub is engineered to be the central nervous system of the modern connected home. It stands as our company's most ambitious consumer product to date, representing a significant advancement in smart home technology. 'Nova' is more than just a device for connecting gadgets; it is an intelligent platform designed to learn, adapt, and create a truly seamless and responsive living environment. Its development was driven by a vision to move beyond simple automation and toward a home that actively anticipates and serves the needs of its inhabitants.\n\nAt the heart of 'Nova' is its powerful voice control engine. This feature allows users to manage their entire smart home ecosystem with natural, intuitive voice commands. We have invested heavily in natural language processing to ensure the system is not only responsive but also understands complex commands and context. This hands-free control liberates users from needing to interact with multiple apps or interfaces, consolidating the management of their home into a single, effortless experience.\n\nA key pillar of the 'Nova' platform is its unparalleled integration capability. The hub is designed to be compatible with over 500 smart devices from a wide range of manufacturers. This open-ecosystem approach ensures that users are not locked into a single brand and can continue to use the smart lights, thermostats, cameras, and other gadgets they already own and love. This extensive compatibility makes 'Nova' one of the most versatile and future-proof smart home hubs available on the market.\n\nThe most groundbreaking feature of the 'Nova' hub is its adaptive learning module. This sophisticated AI-powered system observes user behaviors, routines, and preferences over time. It learns, for example, what time you typically wake up, what your preferred lighting and temperature settings are, and what music you enjoy in the evening. By understanding these patterns, 'Nova' can begin to automate these actions proactively, creating a personalized home environment that runs itself with minimal user intervention.\n\nIn essence, the 'Nova' smart home hub is not just a product; it's a lifestyle enhancement. It promises to reduce complexity, increase comfort, and provide a new level of convenience for our customers. By combining advanced voice control, extensive third-party integration, and a unique adaptive learning module, 'Nova' is poised to set a new standard for what a smart home can and should be."
  },
  {
    title: "Q2 2024 Financial Performance: A Quarter of Significant Growth",
    content: "The company's financial results for the second quarter of 2024 demonstrate a period of robust health and exceptional performance. We are pleased to report a significant 15% increase in total revenue compared to the same period last year. This impressive growth is a direct reflection of our successful strategic initiatives, the hard work of our teams across the globe, and the increasing demand for our products in key international territories. This result surpasses our initial forecasts and sets a positive tone for the remainder of the fiscal year.\n\nA primary driver of this revenue surge was the outstanding performance of our sales division in the European market. Strategic investments in regional marketing, localization of our product offerings, and the expansion of our distribution network have yielded remarkable results. Sales in Europe grew by over 25% quarter-over-quarter, indicating that our brand is resonating strongly with European consumers. This success validates our international expansion strategy and highlights a significant opportunity for continued growth in the region.\n\nThis strong top-line growth has translated directly into a healthy bottom line. The company achieved a net profit of $12 million for the quarter. This figure represents a healthy profit margin and demonstrates our ability to scale our operations efficiently while maintaining fiscal discipline. The profitability is a result of not only increased sales but also careful cost management and operational efficiencies gained through recent process improvements.\n\nThese positive financial results provide us with the capital and the confidence to continue investing in key areas of the business. We will be allocating resources toward research and development to fuel our pipeline of innovative new products. Furthermore, we will continue to build upon our success in Europe while also exploring opportunities in other emerging markets. This strong financial foundation enables us to pursue our long-term growth objectives from a position of strength.\n\nIn summary, the Q2 2024 earnings report paints a very positive picture of the company's current state. The 15% revenue growth and $12 million net profit are clear indicators that our strategy is effective and our execution is strong. We are particularly encouraged by the exceptional results from our European operations and look forward to building on this momentum in the coming quarters."
  },
  {
    title: "Enhancing Security: Our Mandatory Access Protocols",
    content: "In today's digital landscape, protecting our company's sensitive information and systems is of paramount importance. To that end, we have established a comprehensive security protocol that is mandatory for all employees. This protocol is designed to safeguard our digital assets from unauthorized access and potential cyber threats. Adherence to these measures is not optional; it is a critical component of every employee's responsibility to the company and to the security of our collective data.\n\nA cornerstone of our security policy is the requirement for all employees to change their system passwords every 90 days. Regular password updates are a proven method for mitigating the risk associated with compromised credentials. This policy helps to ensure that even if a password were to be exposed, its useful lifespan for a potential attacker is strictly limited. We understand this may require a small effort, but it is a vital step in maintaining a secure environment for everyone.\n\nTo further fortify our defenses, we have implemented mandatory two-factor authentication (2FA) for accessing all internal systems. 2FA adds a critical second layer of security beyond just a password. It requires users to provide a second form of verification, typically a code sent to their mobile device, before granting access. This measure ensures that even if a malicious actor obtains an employee's password, they will be unable to access our systems without physical possession of the employee's registered device.\n\nThe IT department has deployed tools and resources to make adherence to these protocols as seamless as possible. Employees will receive automated reminders before their 90-day password expiration date, and the process for setting up 2FA is straightforward and well-documented. Support is readily available for any employee who encounters difficulties or has questions about implementing these security measures. Our goal is to make security a shared and manageable responsibility.\n\nCompliance with these security protocols is essential for protecting our intellectual property, customer data, and financial information. Non-compliance can create significant vulnerabilities that put the entire organization at risk. We trust that all employees will understand the critical importance of these measures and will diligently follow the password and two-factor authentication requirements to help us maintain a secure and resilient digital workplace."
  },
  {
    title: "Annual Company Offsite: Reconnecting in Lisbon",
    content: "We are thrilled to announce that the annual company offsite for this year will be held in the beautiful and vibrant city of Lisbon, Portugal. This much-anticipated event is scheduled to take place from October 3rd to October 5th. The offsite is a unique opportunity for us to step away from our daily routines, connect with colleagues from across the organization in a relaxed setting, and align on our shared vision for the future. It is a cornerstone of our company culture, designed to foster collaboration, boost morale, and celebrate our collective achievements.\n\nThe purpose of the annual offsite extends beyond just a change of scenery. It is a strategic investment in our people and our culture. The agenda will feature a mix of strategic planning sessions, cross-departmental workshops, and team-building activities. These sessions are designed to spark innovation, improve communication, and ensure that every employee feels connected to the company's mission and goals. It is a time for us to think big, share ideas, and strengthen the bonds that make our teams successful.\n\nLisbon was chosen as this year's destination for its rich history, dynamic culture, and excellent facilities. The city will provide an inspiring backdrop for our activities and give us all a chance to experience something new together. We believe that a stimulating environment is key to fostering creativity and building lasting memories. We are confident that the charm and energy of Lisbon will contribute to making this our most successful offsite yet.\n\nOur dedicated Human Resources department is managing all the logistics to ensure a smooth and enjoyable experience for everyone. They are currently finalizing all travel and accommodation details. Employees can expect to receive a comprehensive information package next week, which will include flight itineraries, hotel information, a detailed agenda for the three days, and guidance on any necessary preparations. The HR team is committed to making this a hassle-free and memorable trip for all attendees.\n\nWe strongly encourage everyone to clear their schedules and prepare for three days of inspiration, collaboration, and fun. The annual offsite is a highlight of our company calendar and a powerful way to reinforce our shared identity and purpose. We look forward to seeing all of you in Lisbon this October as we work and celebrate together, strengthening our team for the year ahead."
  },
  {
    title: "The 'Orion' Update: A Major Leap in Performance and Features",
    content: "We are excited to announce the upcoming release of the 'Orion' software update for our flagship product, scheduled to be rolled out to all customers on September 1st. This update is one of the most significant we have ever developed, representing a major leap forward in both performance and functionality. The 'Orion' update is the culmination of months of dedicated work by our engineering team, aimed at refining the user experience and delivering powerful new capabilities directly requested by our most valuable asset: our customers.\n\nA primary focus of the 'Orion' update has been on deep-level performance enhancements. Our engineers have optimized the core architecture of the software to deliver a faster, more responsive, and more reliable experience. Users will notice significant improvements in loading times, smoother transitions between features, and increased stability across the entire platform. These under-the-hood improvements are designed to make the product feel more fluid and efficient in day-to-day use.\n\nBeyond the performance boosts, 'Orion' introduces three major new features that have been consistently requested by our user community. We have listened carefully to your feedback, and this update is a direct response to your most popular suggestions. These new features are designed to address key user needs, expand the product's capabilities in meaningful ways, and unlock new workflows that were not previously possible. We are confident that these additions will be incredibly well-received and will significantly enhance the value of our product.\n\nThe rollout of the 'Orion' update will be conducted in a phased manner to ensure a smooth and stable transition for all users. The process will begin on September 1st, and we will be closely monitoring system performance and user feedback throughout the rollout period. Our customer support and technical teams will be on high alert to assist with any questions or issues that may arise, ensuring that every user's transition to the new version is as seamless as possible.\n\nThe 'Orion' update reaffirms our commitment to continuous improvement and our dedication to listening to our customers. It is a testament to our philosophy that the best products are built in partnership with the people who use them every day. We are incredibly proud of the work that has gone into this release and are excited for our customers to experience the enhanced performance and powerful new features of the 'Orion' update."
  },
  {
    title: "Exceeding Expectations: Our Customer Support Performance",
    content: "We are exceptionally proud of the performance and dedication demonstrated by our customer support team. A key metric we use to gauge our effectiveness is the average first-response time, which is the time it takes for a customer to receive an initial, meaningful response after submitting a support inquiry. Our performance in this area has been nothing short of stellar, consistently setting a high bar for excellence within our industry and reflecting our deep commitment to customer satisfaction.\n\nAll of our customer interactions and response times are meticulously tracked and analyzed using the 'Zendesk' platform. This powerful tool provides us with real-time data and insights into our support operations, allowing us to monitor performance, identify trends, and continuously refine our processes. The use of Zendesk ensures that we have an accurate, data-driven view of our performance and can hold ourselves accountable to the high standards we have set.\n\nCurrently, our team is maintaining an average first-response time of under two hours. This is a remarkable achievement that significantly exceeds the official company goal, which is set at a respectable four hours. To be operating at a speed that is more than twice as fast as our target is a testament to the efficiency, expertise, and proactive nature of our support professionals. It shows a team that is not content with just meeting goals, but is driven to consistently surpass them.\n\nThis rapid response time has a direct and profound impact on the customer experience. When customers receive a quick and helpful response, it builds trust, reduces frustration, and reinforces their confidence in our brand and our products. It demonstrates that we value their time and are committed to resolving their issues promptly. This level of service is a key differentiator for our company and a significant contributor to our high rates of customer loyalty and retention.\n\nWe want to extend our sincere congratulations and gratitude to the entire customer support team for their outstanding work. Their ability to consistently exceed our response time goals while maintaining a high quality of service is a critical component of our company's success. This achievement is a clear signal to our customers that they are our top priority, and we are dedicated to providing them with the best possible support experience."
  }
];